name: Griplog
options:
  bundleIdPrefix: com.shimondeitel.gripstrength
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  Griplog:
    type: application
    platform: iOS
    sources:
      - path: Griplog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.gripstrength
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Griplog/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  GriplogTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: GriplogTests
      - path: Griplog.storekit
    dependencies:
      - target: Griplog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.gripstrength.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  GriplogUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: GriplogUITests
    dependencies:
      - target: Griplog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.gripstrength.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  Griplog:
    build:
      targets:
        Griplog: all
        GriplogTests: [test]
        GriplogUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: Griplog.storekit
    test:
      config: Debug
      storeKitConfiguration: Griplog.storekit
      targets:
        - GriplogTests
        - GriplogUITests
    archive:
      config: Release
